import React from 'react'
import Navbar from '../components/navbar'

import './styles.scss'

export default function Home() {
  return (
    <div className='home'>
        <Navbar/>

<img width={'100%'} src="https://scontent.fjpa11-1.fna.fbcdn.net/v/t1.6435-9/119462269_2818109058290214_5155477187505806219_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeGTirAhhamCoV5hkv46VG9qxqbfONnuDFPGpt842e4MU1Xp-pJ7bulPWdPi493vXAxd3_sPEj2mHIekygimd29z&_nc_ohc=tufLsXZRvT8AX-khQvT&_nc_ht=scontent.fjpa11-1.fna&oh=00_AT_wkGCDgRh0xNsyDA3Suw98SEH_pQh5AOhLEctkREz2HA&oe=628A6087" alt="" />
     
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum ut maiores recusandae non dignissimos dolores magni nostrum sint, doloribus ex autem ratione necessitatibus dicta debitis porro dolorum? Itaque, iure impedit?
    </div>
  )
}
